project:
  type: website
  output-dir: docs
  
website:
  title: "NBI en Ecuador"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: data_cleaning.qmd
        text: Preparación y exploración de datos
      - href: visualizations.qmd
        text: Análisis y Visualizaciones

format:
  html:
    theme: cosmo
    toc: true
    mermaid:
      securityLevel: loose
    anchor-sections: false
